[package]

name = "utp"
version = "0.6.0"
authors = ["Ricardo Martins <ricardo@scarybox.net>"]

description = "A ÂµTP (Micro/uTorrent Transport Library) library implemented in Rust"
homepage = "https://github.com/meqif/rust-utp"
repository = "https://github.com/meqif/rust-utp"
documentation = "http://meqif.github.io/rust-utp"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["utp", "networking", "protocol", "transport"]

[dependencies]
time = "*"
num = "*"
log = "0.3"
env_logger = "0.3"
rand = "0.3"

[dependencies.with_read_timeout]
path = "with_read_timeout"
version = "*"

[dev-dependencies]
quickcheck = "*"

[lib]
name = "utp"
